Repository camptocamp/ngeo, pull requests merged in 2020-09, with the labels that each got.

#6223 Fix duplicated STYLES parameter in print requests
  src/print/Service.js
  test/spec/services/print.spec.js
Labels: backport 2.5, backport master

#6270 Add missing dependency required by ls
  package.json
Labels: backport 2.4, backport 2.5

#6261 Params.STYLES can present but undefined
  src/print/Service.js
Labels: backport 2.4, backport master
