Repository camptocamp/ngeo, pull requests merged in 2020-11, with the labels that each got.

#6423 Fix PR lint action
  .github/workflows/pr-title-lint.yaml
Labels: backport 2.4, backport 2.5

#6430 Adding ability to specify a layer in measure.
  src/interaction/Measure.js
  src/interaction/MeasureBaseOptions.js
Labels: backport master

#6477 Better work around for ctrlKey events
  src/utils.js
Labels: backport master

#6429 Enable to change the xy order on getFeature GML format
  contribs/gmf/src/datasource/Manager.js
  contribs/gmf/src/editing/Snapping.js
  contribs/gmf/src/themes.js
  src/datasource/OGC.js
Labels: backport 2.5, backport master

#6486 WMTS opacity on background layers
  contribs/gmf/src/theme/Themes.js
  src/map/LayerHelper.js
Labels: backport master
