Repository camptocamp/ngeo, pull requests merged in 2020-05, with the labels that each got.

#5785 Add missing dependency for prettier
  package.json
Labels: backport master

#5793 No Javascript error on first click
  contribs/gmf/src/drawing/drawFeatureOptionsComponent.js
Labels: backport master

#5794 No error on click on missing data
  src/googlestreetview/component.js
Labels: backport master

#5802 Set default style on the features
  api/src/Map.js
Labels: backport 2.4, backport master

#5812 Fix for WMTS layer name
  contribs/gmf/src/datasource/ExternalDataSourcesManager.js
Labels: backport 2.5, backport master

#5553 [api] Fix getFeaturesFromIds when GMF and WMS layers do not have the …
  api/src/Querent.js
Labels: backport 2.5, backport master

#5876 Fix missing API help
  buildtools/publish
Labels: backport master
