Repository camptocamp/ngeo, pull requests merged in 2020-07, with the labels that each got.

#5998 Allow the open LayerTree expanded by default
  contribs/gmf/apps/mobile-ref.png
  contribs/gmf/src/layertree/component.html
  contribs/gmf/src/layertree/component.js
Labels: backport master

#6002 Retry example check
  Makefile
  buildtools/retry
Labels: backport 2.5

#6008 Fix message for new GitHub version
  .github/workflows/test_url.yaml
Labels: backport 2.4, backport 2.5

#6012 Add name to external layer services
  contribs/gmf/src/import/importdatasourceComponent.js
Labels: backport master

#6009 Gui for swipe on layertree groups gsgmf 1336
  contribs/gmf/src/layertree/common.scss
  contribs/gmf/src/layertree/component.html
  contribs/gmf/src/layertree/component.js
Labels: backport master

#6005 Use an image to print RegularShape
  src/print/VectorEncoder.js
  test/spec/services/print.spec.js
Labels: backport master

#6011 Remove snapping icon for mobile
  contribs/gmf/src/layertree/mobile.scss
Labels: backport master

#6007 Add layertree icon tooltips
  contribs/gmf/src/layertree/component.html
Labels: backport master

#6034 Don't hide the cross when there steel have a geometry
  buildtools/check-example.js
  contribs/gmf/examples/editfeature-ref.png
  contribs/gmf/examples/editfeatureselector-ref.png
  contribs/gmf/src/search/component.html
  src/map/FeatureOverlay.js
Labels: backport master

#6033 The search popup should be above the disclamers
  contribs/gmf/src/sass/map.scss
Labels: backport master

#6030 Removes strange and buggy functionality
  contribs/gmf/src/query/windowComponent.html
  contribs/gmf/src/query/windowComponent.js
  src/query/MapQuerent.js
  src/statemanager/WfsPermalink.js
Labels: backport master

#6026 Correct scaleselector with constrainResolution to false
  api/src/Map.js
  contribs/gmf/apps/desktop/Controller.js
  contribs/gmf/apps/desktop_alt/Controller.js
  contribs/gmf/apps/desktop_alt/index.html.ejs
  contribs/gmf/examples/mobilemeasure.js
  contribs/gmf/src/controllers/AbstractAPIController.js
  contribs/gmf/src/controllers/AbstractMobileController.js
  examples/measure.js
  examples/scaleselector-ref.png
  examples/scaleselector.js
  src/map/scaleselector.js
  src/misc/filters.js
  test/spec/directives/scaleselector.spec.js
Labels: backport master

#6031 Fix check of support of opacity on layer
  contribs/gmf/examples/layertree-ref.png
  contribs/gmf/examples/layertreeadd-ref.png
  contribs/gmf/src/layertree/component.js
  src/map/FeatureOverlay.js
Labels: backport master

#6045 Fix full text search colorpicker never disappears
  contribs/gmf/src/search/component.js
Labels: backport master

#6046 Fix Remove all on externals
  contribs/gmf/src/datasource/ExternalDataSourcesManager.js
  contribs/gmf/src/import/importdatasourceComponent.html
  contribs/gmf/src/layertree/component.html
  contribs/gmf/src/layertree/component.js
Labels: backport master

#6053 Typo - Use single pipe for translation
  contribs/gmf/src/layertree/component.html
Labels: backport master

#6078 Fts keep clear button when feature gsgmf 1348
  contribs/gmf/src/search/component.html
  src/map/FeatureOverlay.js
  src/map/FeatureOverlayMgr.js
  test/spec/services/featureoverlay.spec.js
Labels: backport master

#6086 Do not unregister already unregistered file datasources
  src/datasource/FileGroup.js
Labels: backport master

#6082 Corrections after release v2.4.2 geo 3403
  contribs/gmf/apps/desktop_alt/Controller.js
  contribs/gmf/apps/desktop_alt/index.html.ejs
Labels: backport 2.5, backport master
