Repository camptocamp/ngeo, pull requests merged in 2021-02, with the labels that each got.

#6770 Ignore permalink on manual background selection
  contribs/gmf/src/authentication/component.js
  contribs/gmf/src/backgroundlayerselector/component.js
  contribs/gmf/src/backgroundlayerselector/status.js
  contribs/gmf/src/controllers/AbstractAppController.js
  contribs/gmf/src/search/component.js
  contribs/gmf/src/theme/selectorComponent.js
Labels: backport 2.5, backport 2.6, backport master

#6784 Fix typo in scale-selector log
  src/map/scaleselector.js
Labels: backport 2.6, backport master

#6783 Simplify background selection
  contribs/gmf/src/controllers/AbstractAppController.js
Labels: backport master

#6780 Fix permalink: avoid using ng-include
  Makefile
  contribs/gmf/apps/desktop/index.html.ejs
  contribs/gmf/apps/desktop_alt/index.html.ejs
  contribs/gmf/apps/oeedit/header.html
  contribs/gmf/apps/oeedit/index.html.ejs
  contribs/gmf/src/controllers/AbstractDesktopController.js
  contribs/gmf/src/header/component.html
  contribs/gmf/src/header/component.js
  contribs/gmf/src/header/module.js
  contribs/gmf/src/mainmodule.js
Labels: backport 2.6

#6795 Add crossorigin=anonymous on ressources that don't required an autent…
  contribs/gmf/apps/desktop/index.html.ejs
  contribs/gmf/apps/desktop_alt/index.html.ejs
  contribs/gmf/apps/iframe_api/index.html.ejs
  contribs/gmf/apps/mobile/index.html.ejs
  contribs/gmf/apps/mobile_alt/index.html.ejs
  contribs/gmf/apps/oeedit/index.html.ejs
Labels: backport master

#6804 Use alert instead of modal to show changed password (simple message)
  contribs/gmf/src/authentication/component.html
  contribs/gmf/src/authentication/component.js
Labels: backport 2.5, backport 2.6, backport master

#6810 Rename Rule.expression to Rule.literal
  src/filter/RuleHelper.js
  src/filter/component.js
  src/filter/ruleComponent.js
  src/filter/rulecomponent.html
  src/format/filter.js
  src/rule/Date.js
  src/rule/Geometry.js
  src/rule/Rule.js
  src/rule/Select.js
  src/rule/Text.js
Labels: backport master

#6816 2.5 and 2.6 update
  docs/features.md
Labels: backport 2.6

#6811 Rename 'Apply' button in rule creating form
  src/filter/rulecomponent.html
Labels: backport 2.5, backport 2.6

#6835 Fix oeedit with 2d geom GEO-4161
  contribs/gmf/src/objectediting/coordinate.js
Labels: backport 2.5, backport 2.6, backport master

#6840 Fix print text on feature
  src/print/VectorEncoder.js
Labels: backport 2.5, backport master

#6850 Retablish search clear button to true per default
  contribs/gmf/src/search/component.html
  contribs/gmf/src/search/component.js
Labels: backport master

#6851 Typo in print vector encoders
  src/print/VectorEncoder.js
Labels: backport master

#6834 Sum of tabs for too many results text
  contribs/gmf/src/query/gridComponent.html
  contribs/gmf/src/query/gridComponent.js
Labels: backport master
