Repository camptocamp/ngeo, pull requests merged in 2021-11, with the labels that each got.

#7663 Bump jquery-ui who has security issues
  package.json
Labels: backport 2.5, backport 2.6

#7678 Remove solved CVE
  npm-cve-ignore
Labels: backport 2.5, backport 2.6

#7711 Update CVE ids
  ci/config.yaml
  npm-cve-ignore
Labels: backport master, backport 2.5, backport 2.6

#7717 Fix printed legend image - use layer node name
  contribs/gmf/src/print/LegendMapFishPrintV3.js
Labels: backport master
