Repository camptocamp/ngeo, pull requests merged in 2021-06, with the labels that each got.

#7236 Allow to draw elements without the 1 meter limit
  contribs/gmf/src/drawing/drawFeatureOptionsComponent.html
Labels: backport 2.6

#7255 With permalink upper can be NaN
  src/datasource/OGC.js
Labels: backport 2.4, backport 2.5, backport master

#7254 Fix undefined text style for geometries imported from KML
  src/print/VectorEncoder.js
Labels: backport master

#7263 Fix messages in pull requests
  .github/workflows/test_url.yaml
Labels: backport 2.4, backport 2.5, backport master

#7262 Fix no theme after logout
  contribs/gmf/examples/themeselector.html
  contribs/gmf/src/controllers/AbstractAppController.js
Labels: backport master

#7274 Fix static legend on printing
  contribs/gmf/src/objectediting/Query.js
  contribs/gmf/src/print/LegendMapFishPrintV3.js
  contribs/gmf/src/theme/Themes.js
Labels: backport master
