Repository camptocamp/ngeo, pull requests merged in 2022-04, with the labels that each got.

#8308 Add default value for each footer height
  src/canvas/Desktop.stories.ts
  src/canvas/DesktopElement.ts
  src/controllers/vars_desktop.scss
Labels: backport master

#8313 Display & hide disclaimers when a layers is visible/hidden
  src/disclaimer/component.js
Labels: backport master

#8336 Fix arrows drawing keys for translations
  src/drawing/featureStyleComponent.html
  src/misc/FeatureHelper.js
Labels: backport master

#8330 Add gmfSnappingOptions to configure maxFeatures for snapping
  contribs/gmf/examples/options.js
  contribs/gmf/src/editing/Snapping.js
  contribs/gmf/src/options.js
Labels: backport master, backport 2.7

#8348 Fix Google StreetView panel height
  contribs/gmf/apps/desktop_alt/index.html.ejs
  contribs/gmf/apps/desktop_alt/sass/desktop_alt.scss
Labels: backport master

#8354 Fix CVE
  package.json
Labels: backport 2.5, backport 2.6, backport 2.7

#8350 Fix password reset and remove theme reloading at password reset
  src/auth/FormElement.ts
  src/auth/service.ts
  src/controllers/AbstractAppController.js
Labels: backport master

#8380 Ignore audit on fast-sass-loader
  ci/config.yaml
Labels: backport master, backport 2.5, backport 2.6, backport 2.7

#8388 Fix LIDAR profile
  src/controllers/desktop.scss
  src/lidar/FooterElement.ts
Labels: backport master

#8418 Set grid-gutter-width variable in the CSS
  src/sass/vars_only.scss
Labels: backport master

#8420 Add bufferSize parameter to mapillary options in example
  examples/mapillarystreetview.js
Labels: backport master, backport 2.7

#8439 Makes body element focusable for onKeyDown event
  contribs/gmf/apps/desktop_alt/index.html.ejs
Labels: backport master, backport 2.6
