Repository camptocamp/ngeo, pull requests merged in 2022-09, with the labels that each got.

#8822 Be able to have second-level group active when added with FTS
  src/layertree/TreeManager.js
Labels: backport 2.7

#8828 Add labels to number field for directedFilterAttributes
  src/controllers/desktop.scss
  src/filter/rulecomponent.html
  src/sass/filters.scss
Labels: backport master

#8830 Allow the filter button to open the panel from the layertree
  src/filters/filterselectorComponent.js
Labels: backport master

#8845 Fix external datasource url
  src/datasource/ExternalDataSourcesManager.js
Labels: backport master

#8848 Update the Renovate configuration
  .github/renovate.json5
Labels: chore
