Repository camptocamp/ngeo, pull requests merged in 2022-11, with the labels that each got.

#8900 Fix repository in workflow used to delete old workflow runs
  .github/workflows/delete-old-workflows-run.yaml
Labels: chore

#8903 Ignore CVE on loader-utils
  ci/config.yaml
Labels: backport 2.6

#8910 Add or update pull request check on stabilization branch
  .github/workflows/pr-checks.yaml
Labels: chore

#8912 Add or update pull request check on stabilization branch
  .github/workflows/pr-checks.yaml
Labels: chore

#8911 Add or update pull request check on stabilization branch
  .github/workflows/pr-checks.yaml
Labels: chore

#8915 Fix auto-review on stabilization of the branch for Renovate pull requests
  .github/workflows/auto-review.yaml
Labels: chore

#8913 Fix auto-review on stabilization of the branch for Renovate pull requests
  .github/workflows/auto-review.yaml
  .github/workflows/dependabot-auto-merge.yaml
Labels: chore

#8914 Fix auto-review on stabilization of the branch for Renovate pull requests
  .github/workflows/auto-review.yaml
  .github/workflows/dependabot-auto-merge.yaml
Labels: chore

#8928 Fix min size on query window
  src/query/windowComponent.js
Labels: backport master, bug

#8930 Replace deprecated --no-optional with --omit=optional
  Makefile
Labels: chore

#8932 [Snyk] Upgrade @types/node from 17.0.41 to 17.0.45
  package.json
Labels: dependencies

#8933 Upgrade deprecated set-output commands
  .github/workflows/main.yaml
Labels: chore
