Repository camptocamp/ngeo, pull requests merged in 2022-03, with the labels that each got.

#8187 Set the print panel closed when we reduce it
  src/controllers/AbstractDesktopController.js
Labels: backport 2.6

#8189 Edition: Fix undefined boolean to false
  src/editing/attributesComponent.js
Labels: backport 2.4, backport 2.5

#8201 Catch error on WFS query promise (in snapping)
  contribs/gmf/src/editing/Snapping.js
Labels: backport master

#8208 Add missing reject in deferrableOnSuccessfulLogin
  contribs/gmf/src/authentication/Service.js
Labels: backport master

#8255 Fix LIDAR PNG export error
  src/lidar/Utils.ts
Labels: backport 2.7

#8264 Do not overwrite metadata while restoring layertree state
  contribs/gmf/src/layertree/TreeManager.js
  contribs/gmf/src/layertree/component.html
Labels: backport master, backport 2.7

#8297 Fix missing bottom of the queryresult footer
  src/controllers/vars_desktop.scss
Labels: backport master
