Repository camptocamp/ngeo, pull requests merged in 2022-10, with the labels that each got.

#8859 Fix multiline messages
  src/permalink/shareComponent.html
Labels: backport master

#8867 Fix the checkout user to be able to create pull request for Snyk fix
  .github/workflows/audit.yaml
Labels: chore

#8885 Add workflow to delete old workflow runs
  .github/workflows/delete-old-workflows-run.yaml
Labels: chore

#8896 Fix layer changing order when printing with legend
  src/print/LegendMapFishPrintV3.js
Labels: backport 2.6, backport 2.7
