Repository camptocamp/ngeo, pull requests merged in 2023-03, with the labels that each got.

#9033 Restore onSuccessulLogin method
  src/auth/service.ts
Labels: backport master, backport 2.8

#9042 Update precommit hooks
  .pre-commit-config.yaml
Labels: chore

#9044 Fix new error with attr in pull request check workflow
  .github/workflows/pr-checks.yaml
Labels: chore

#9043 Fix pushUnlessIncluded function
  src/array.js
Labels: backport 2.8

#9041 Log the theme error as warning
  .pre-commit-config.yaml
  src/theme/Themes.js
Labels: backport master

#9040 Remove Snyk pinning
  ci/requirements.txt
  requirements.txt
Labels: chore

#9037 Create an empty style if he doesn't exists
  src/print/Service.js
Labels: backport master, backport 2.7

#9060 Don't re-open a manually closed disclaimer
  src/message/Disclaimer.js
  src/message/Message_OLD.js
Labels: backport master, backport 2.8

#9064 Update pre-commit-hook version
  .pre-commit-config.yaml
Labels: backport master, backport 2.8

#9070 Allow dimensions to be passed for WMS layers in background group
  src/datasource/Manager.js
Labels: backport master, backport 2.8
