Repository camptocamp/ngeo, pull requests merged in 2023-04, with the labels that each got.

#9084 Handle error on failing CSV export in LiDAR panel
  src/lidar/PanelElement.ts
Labels: backport master, backport 2.8

#9090 Fix example checks
  .pre-commit-config.yaml
  buildtools/check-example.js
  buildtools/sgx.capabilities.xml
  contribs/gmf/examples/backgroundlayerselector-ref.png
  contribs/gmf/examples/themeselector-ref.png
Labels: backport master

#9094 Fix the phantom disclaimer
  src/disclaimer/component.js
  src/layertree/Controller.js
  src/layertree/TreeManager.js
  src/message/Disclaimer.js
Labels: backport master, backport 2.7

#9089 Clear the WebGL rendering correctly
  examples/mapswipe-ref.png
  examples/mapswipe.css
  examples/mapswipe.html
  examples/mapswipe.js
  src/map/swipe.js
Labels: backport master

#9092 Add the floor in the mobile for simple app
  buildtools/webpack.dist.js
  contribs/gmf/apps/mobile_alt/Controller.js
Labels: backport master

#9091 Fix blurry WMS and WMTS layers
  api/src/Map.js
  contribs/gmf/examples/options.js
  contribs/gmf/test/spec/beforeeach.js
  examples/options.js
  src/controllers/AbstractAppController.js
  src/layertree/SyncLayertreeMap.js
  src/options.js
  src/proj/EPSG_2056.js
  src/proj/EPSG_21781.js
  src/proj/utils.js
  src/theme/Themes.js
Labels: backport master
