Repository camptocamp/ngeo, pull requests merged in 2023-02, with the labels that each got.

#9007 Do the pull request at the end of the day
  .github/renovate.json5
Labels: chore

#9008 Do the pull request at the end of the day
  .github/renovate.json5
Labels: chore

#9011 Configure pre-commit auto update schedule
  .pre-commit-config.yaml
Labels: chore

#9012 Fix check connection
  src/auth/service.ts
Labels: backport 2.7

#9017 Fix simple bootstrap
  src/controllers/bootstrap.js
Labels: backport master, backport 2.8

#9014 Documentation: fix the hi DPI explanation
  src/print/component.js
  src/themes.js
Labels: backport 2.7, backport 2.8
