Repository camptocamp/ngeo, pull requests merged in 2023-12, with the labels that each got.

#9266 Be able to set the arcgisWMSInfoFormat per ogcServer
  src/datasource/Manager.js
  src/options.js
  srcapi/store/config.ts
Labels: backport master, backport 2.8

#9269 Fix for index == 0
  src/format/ArcGISGeoJSON.js
Labels: backport master

#9271 Fix used ogcServerName
  src/datasource/Manager.js
Labels: backport master, backport 2.8

#9274 Fix error on search result selection with coordinates search
  src/controllers/AbstractAppController.js
Labels: backport master, backport 2.7
