Repository camptocamp/ngeo, pull requests merged in 2025-04, with the labels that each got.

#9698 Clean the branch before writing on it
  .github/workflows/main.yaml
Labels: backport 2.7, backport 2.8, backport 2.9

#9697 Fix application context on OIDC login
  src/auth/FormElement.ts
  src/statemanager/Location.js
Labels: backport master

#9722 Send optional VERSION from OGCServer URL in print spec
  Makefile
  src/print/Service.js
Labels: backport master, backport 2.9
