Repository camptocamp/ngeo, pull requests merged in 2025-02, with the labels that each got.

#9584 Remove double import of jquery-datepicker
  src/editing/editFeatureComponent.js
  srcapi/elements/BaseElement.ts
Labels: backport 2.9

#9597 Move date-picker popover above the resize-panel-left button
  src/sass/popover.scss
Labels: backport 2.9

#9586 Disable tracking based on distance in pixel
  src/geolocation/component.js
Labels: backport master

#9570 Fix npm install on Ubuntu 24.04
  Makefile
  README.md
Labels: backport master, backport 2.9

#9605 Store the tools panel size
  src/canvas/DesktopElement.ts
Labels: backport master

#9612 Remove angular-ui - refactor time input
  CHANGES.md
  buildtools/check-example.js
  buildtools/compile-catalog.js
  buildtools/webpack.commons.js
  buildtools/webpack.config.dll.js
  contribs/gmf/examples/datepicker-ref.png
  contribs/gmf/examples/datepicker.html
  contribs/gmf/examples/datepicker.js
  contribs/gmf/examples/datepicker.scss
  contribs/gmf/examples/importdatasource-ref.png
  contribs/gmf/examples/importdatasource.scss
  contribs/gmf/examples/layertree-ref.png
  contribs/gmf/examples/layertree.scss
  contribs/gmf/examples/layertreeadd-ref.png
  contribs/gmf/examples/layertreeadd.scss
  contribs/gmf/examples/timeslider-ref.png
  contribs/gmf/examples/timeslider.html
  contribs/gmf/examples/timeslider.js
  contribs/gmf/examples/timeslider.scss
  examples/datepicker-ref.png
  examples/datepicker.html
  examples/datepicker.js
  examples/datepicker.scss
  package-lock.json
  package.json
  src/controllers/AbstractAppController.js
  src/controllers/desktop.scss
  src/datasource/OGC.js
  src/filter/ruleComponent.js
  src/filter/rulecomponent.html.js
  src/layertree/component.html.js
  src/layertree/component.js
  src/layertree/module.js
  src/layertree/timeSliderComponent.js
  src/layertree/timeslider.scss
  src/layertree/timesliderComponent.html.js
  src/misc/common-jquery-dependencies.js
  src/misc/datepickerComponent.html.js
  src/misc/datepickerComponent.js
  src/misc/extraModule.js
  src/sass/components.scss
  src/sass/datepicker.scss
  src/time-input/datepicker.ts
  src/time-input/time-input.ts
  src/time-input/timeslider.ts
Labels: backport master

#9615 GSGMF-2138-time-input: handle angular part in angular
  contribs/gmf/examples/datepicker.html
  contribs/gmf/examples/datepicker.js
  contribs/gmf/examples/timeslider.html
  contribs/gmf/examples/timeslider.js
  src/controllers/AbstractAppController.js
  src/filter/ruleComponent.js
  src/filter/rulecomponent.html.js
  src/layertree/component.html.js
  src/layertree/component.js
  src/misc/customEventDirective.ts
  src/time-input/datepicker.ts
  src/time-input/time-input.ts
  src/time-input/timeslider.ts
Labels: backport master
