Repository camptocamp/ngeo, pull requests merged in 2025-03, with the labels that each got.

#9619 Fallback tiles without WebGL
  src/datasource/Manager.js
  src/editing/editFeatureComponent.js
  src/layertree/SyncLayertreeMap.js
  src/layertree/component.js
  src/map/LayerHelper.js
  src/objectediting/component.js
  src/print/LegendMapFishPrintV3.js
  src/print/Service.js
  src/utils.js
Labels: backport master, backport 2.9

#9629 Fix Font Awesome moving icon
  Makefile
  src/drawing/drawFeatureComponent.js
  src/editing/editFeatureComponent.js
  src/filter/ruleComponent.js
  src/statemanager/WfsPermalink.js
Labels: backport master

#9630 Remove extra char
  src/layertree/component.html.js
Labels: backport master

#9633 Fix black outline on drawn polygon with annotation
  src/print/VectorEncoder.js
Labels: backport master, backport 2.8

#9640 Disable modifying geometry if 'geom' is part of readonlyAttributes
  src/editing/attributescomponent.html.js
  src/editing/editFeatureComponent.js
  src/misc/FeatureHelper.js
Labels: backport 2.9
